# Homework 1 - Numpy

For all the questions, print the results with a variable of your choice (e.g., Z)

#### 1. Import the numpy package under the name `np` 

In [262]:
import numpy as np

#### 2. Create a vector with values ranging from 10 to 49 

In [263]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 3. Reverse a vector (first element becomes last) 

In [264]:
a = np.arange(10,50)
b = a[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 4. Create a 3x3 matrix with values ranging from 0 to 8 

In [265]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 5. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [266]:
a = [1,2,0,0,4,0]
b = np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int32),)


#### 6. Create a 3x3 identity matrix 

In [267]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 7. Create a 3x3x3 array with random values 

In [268]:
a = np.random.rand(3,3,3)
print(a)

[[[0.6695369  0.6578961  0.60842904]
  [0.68730395 0.17186934 0.9511081 ]
  [0.96624248 0.92931053 0.49562022]]

 [[0.85132645 0.82647823 0.54807175]
  [0.62979177 0.29226271 0.13916067]
  [0.05143261 0.92146141 0.08479099]]

 [[0.7217928  0.6857768  0.20394668]
  [0.24508951 0.26736546 0.03584151]
  [0.92311496 0.60565908 0.69750898]]]


#### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [269]:
a = np.random.rand(10,10)
a_min, a_max = a.min(), a.max()
print("minimum = {}, maximum = {}".format(a_min, a_max))

minimum = 0.013823232145577236, maximum = 0.9989771967140852


#### 9. Create a checkerboard 8x8 matrix using np.array([0,1],[1,0]) and the tile function  

In [270]:
a = np.array([[0,1], [1,0]])
a_tile = np.tile(a, (4,4))
print(a_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [271]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
print(a.dot(b))

[[1.16578554 0.59305969]
 [1.32609316 0.78385247]
 [0.66760474 0.34386568]
 [0.56406705 0.33810996]
 [0.88811169 0.41829433]]


#### 11. Create a 5x5 matrix with row values ranging from 0 to 4 using tile function as follows:


In [272]:
a = np.arange(5)
a_tile = np.tile(a, (5,1))
print(a_tile)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 12. Create a 5x5 matrix with row values ranging from 0 to 4 using broadcasting


In [273]:
a = np.arange(5)
b = np.zeros((5,1))
print(a+b)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 13. Create a random vector of size 10 and sort it 

In [274]:
a = np.random.rand(10)
a.sort()
print(a)

[0.08902054 0.12155803 0.29573653 0.47402021 0.5141962  0.56498462
 0.59243438 0.78712221 0.82615233 0.9926331 ]


#### 14. Subtract the mean of each row

X = np.random.rand(5,10)

In [286]:
X = np.random.rand(5,10)
Y = X - X.mean(axis=1).reshape(-1,1)
print(Y)

[[-0.43591438 -0.18721642  0.025914   -0.34609399  0.32582797 -0.30366821
   0.47451977  0.08098642  0.39844371 -0.03279887]
 [ 0.23024131  0.0383384  -0.34789008  0.51058979 -0.15652051 -0.07041045
  -0.35400924  0.18553731  0.21553564 -0.25141216]
 [ 0.18931556 -0.10733252  0.42745831 -0.16667377 -0.50524222 -0.34958069
   0.22283454 -0.00436784 -0.10025945  0.39384807]
 [ 0.06068232 -0.26071168  0.25822575  0.06035371 -0.13162006 -0.42569524
   0.13654278  0.07512825  0.36427703 -0.13718285]
 [ 0.08961214 -0.20803399  0.24844794 -0.17558859 -0.06610619  0.30008485
  -0.1492873   0.15484235  0.08468384 -0.27865503]]


#### 15. Create, 10 by 10 multiplication table from 1 to 10

In [276]:
a = np.arange(1,11)
b = np.arange(1,11).reshape(10,1)
print(a*b)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


#### 16. How to get the diagonal of a dot product? 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [277]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
C = np.diag(A.dot(B))
print(C)

[1.12982149 1.87546688 1.01304587 1.65411977 1.09959497]


#### 17. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [278]:
a = np.array([1,2,3,4,5])
a_0 = np.zeros(len(a) + (len(a)-1)*3)
a_0[::4] = a
print(a_0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 18. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

#### 19. How to swap two rows of an array? Generate an array from 0 to 24, and reshape it 5 by 5 and swap first two rows of the array

In [279]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 20. How to find the most frequent value in an array? 

Z = np.random.randint(0,10,50). hint: np.bincount, np.argmax

In [280]:
Z = np.random.randint(0,10,50)
print(Z)
print("The most frequent value = {}".format(np.bincount(Z).argmax()))

[6 1 8 9 8 0 5 6 0 0 6 8 2 2 6 4 1 4 6 0 6 7 5 8 3 2 5 8 5 1 9 7 8 5 3 8 1
 7 9 3 4 3 5 3 0 0 8 5 8 7]
The most frequent value = 8


#### 21. How to get the n largest values of an array?

start with 
Z = np.arange(10000);
np.random.shuffle(Z)
, Hint: np.argsort

In [281]:
Z = np.arange(10000)
np.random.shuffle(Z)
print(Z)
n = 4

print("The {} largest values = {}".format(n, Z[np.argsort(Z)[-n:]]))

[6137  128 3128 ... 6477 4813 6619]
The 4 largest values = [9996 9997 9998 9999]


#### 22. Given a two dimensional array, how to extract unique rows? 

Hint: np.unique

In [282]:
a = np.random.randint(1,5,(1000,2))
np.unique(a, axis=0)

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4]])

#### 23. How to compute averages using a sliding window over an array? 

make a function with two arguments, arry and size of the sliding window, def moving_avg(arr, n)


In [288]:
def moving_avg(arr,n):
    print("array = {}, size = {}".format(arr,n))
    L = []
    for i in range(0,(len(arr)-n+1)):
        L.append(np.mean(arr[i:i+n]))
    return L

a = [1,2,2,3,5,6,7]
b = 2

moving_avg(a,b)

array = [1, 2, 2, 3, 5, 6, 7], size = 2


[1.5, 2.0, 2.5, 4.0, 5.5, 6.5]

#### 24. Find the indices of elements from 4 by 4 random matrix (0-1) which are larger than 0.5

Print a list of tuples indicating the index for row and column


In [284]:
a = np.random.rand(4,4)
idx = np.nonzero(a>0.5)
print([*zip(idx[0],idx[1])])

[(0, 1), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 2), (3, 0), (3, 1), (3, 2)]


#### 25. Write a function returning distance between two points

In [289]:
a = np.random.randint(1,20,size=2)
b = np.random.randint(1,20,size=2)
print("a = {}, b = {}".format(a,b))

def distance_ab(x,y):
    distance = np.sqrt((x[0]-y[0])**2 + (x[1]-y[1])**2)
    return distance

print("distance between two points a,b = {}".format(distance_ab(a,b)))

a = [ 8 12], b = [1 4]
distance between two points a,b = 10.63014581273465
